name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build
            # workingDirectory: $(System.DefaultWorkingDirectory)/p1-tew9

stages:
- stage: analyze
  jobs:
    - job:
      pool:
        vmImage: ubuntu-18.04
      steps:
        task:

        - script: |
            <SSonarScanner.MSBuild.exe begin /k:"tew9" /o:"<tew9>" /d:sonar.login="<token>" 
            dotnet build
            SonarScanner.MSBuild.exe end /d:sonar.login="<token>" 
          env: 
            SONAR_LOGIN: $(sonar_login)

  - stage: test
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            # workingDirectory: ./p1-tew9

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              docker login
              docker image build -f dockerfile -t tangotew/p1-project .
              docker image push tangotew/p1-project
              docker logout
            env:
              DOCKER_IMAGE: $(image_name)
            # workingDirectory: ./p1-tew9
trigger:
  - frontend

variable:
  - image_name: tangotew/p1-project
    # © 2020 GitHub, Inc.
    # Terms
    # Privacy
    # Security
    # Status
    # Help

