// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaBox.ORMData.Database;

namespace PizzaBox.ORMData.Migrations
{
    [DbContext(typeof(PizzaBoxDBContext))]
    [Migration("20200322023242_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.Property<long>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("totPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("orderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Pizza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            Name = "Chicago Deep Dish"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Vegie Pizza"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Chickens Pizza"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Cheese Pizza"
                        },
                        new
                        {
                            Id = 1L,
                            Name = "The Original Neapolitan"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "California Style"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("PizzaOrder");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaSize", b =>
                {
                    b.Property<long>("SizeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("SizeId", "Id");

                    b.HasIndex("Id");

                    b.ToTable("PizzaSize");

                    b.HasData(
                        new
                        {
                            SizeId = 1L,
                            Id = 1L
                        },
                        new
                        {
                            SizeId = 2L,
                            Id = 1L
                        },
                        new
                        {
                            SizeId = 3L,
                            Id = 1L
                        },
                        new
                        {
                            SizeId = 1L,
                            Id = 2L
                        },
                        new
                        {
                            SizeId = 2L,
                            Id = 2L
                        },
                        new
                        {
                            SizeId = 3L,
                            Id = 2L
                        },
                        new
                        {
                            SizeId = 1L,
                            Id = 3L
                        },
                        new
                        {
                            SizeId = 2L,
                            Id = 3L
                        },
                        new
                        {
                            SizeId = 3L,
                            Id = 3L
                        },
                        new
                        {
                            SizeId = 1L,
                            Id = 4L
                        },
                        new
                        {
                            SizeId = 2L,
                            Id = 4L
                        },
                        new
                        {
                            SizeId = 3L,
                            Id = 4L
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaStore", b =>
                {
                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "Id");

                    b.HasIndex("Id");

                    b.ToTable("PizzaStore");

                    b.HasData(
                        new
                        {
                            StoreId = 1L,
                            Id = 1L,
                            Inventory = 5
                        },
                        new
                        {
                            StoreId = 1L,
                            Id = 2L,
                            Inventory = 10
                        },
                        new
                        {
                            StoreId = 1L,
                            Id = 3L,
                            Inventory = 20
                        },
                        new
                        {
                            StoreId = 1L,
                            Id = 4L,
                            Inventory = 6
                        },
                        new
                        {
                            StoreId = 2L,
                            Id = 1L,
                            Inventory = 5
                        },
                        new
                        {
                            StoreId = 2L,
                            Id = 2L,
                            Inventory = 10
                        },
                        new
                        {
                            StoreId = 2L,
                            Id = 3L,
                            Inventory = 20
                        },
                        new
                        {
                            StoreId = 2L,
                            Id = 4L,
                            Inventory = 6
                        },
                        new
                        {
                            StoreId = 3L,
                            Id = 5L,
                            Inventory = 6
                        },
                        new
                        {
                            StoreId = 3L,
                            Id = 6L,
                            Inventory = 4
                        },
                        new
                        {
                            StoreId = 3L,
                            Id = 1L,
                            Inventory = 7
                        },
                        new
                        {
                            StoreId = 3L,
                            Id = 2L,
                            Inventory = 6
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Size", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Large",
                            Price = 13.75m
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Medium",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Small",
                            Price = 8.25m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Dominos",
                            UserId = 2L,
                            location = "123 bcd st, Arlington tx"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Pizza Hut",
                            UserId = 3L,
                            location = "456 DeF, Arlington Tx"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Papa John's",
                            UserId = 3L,
                            location = "456 DeF, Arlington Tx"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "tango",
                            email = "tango@gmail.com",
                            lastname = "Tew",
                            password = "123",
                            type = "user",
                            username = "tango"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Andrew",
                            email = "tango@gmail.com",
                            lastname = "AGatep",
                            password = "123",
                            type = "user",
                            username = "drew"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Mark",
                            email = "mark@gmail.com",
                            lastname = "John",
                            password = "456",
                            type = "store",
                            username = "mark"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Dr. Frank",
                            email = "fred@gmail.com",
                            lastname = "Fred",
                            password = "123",
                            type = "store",
                            username = "fred"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "William",
                            email = "john@gmail.com",
                            lastname = "John",
                            password = "123",
                            type = "store",
                            username = "john"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaOrder", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "Pizza")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Order", "Order")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaSize", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "Pizza")
                        .WithMany("PizzaSizes")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Size", "Size")
                        .WithMany("PizzaSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaStore", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "pizza")
                        .WithMany("PizzaStores")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Store", "Store")
                        .WithMany("PizzaStore")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Store", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
