// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaBox.ORMData.Database;

namespace PizzaBox.ORMData.Migrations
{
    [DbContext(typeof(PizzaBoxDBContext))]
    partial class PizzaBoxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("totPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Pizza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            Name = "Chicago Deep Dish",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Vegie Pizza",
                            Price = 13.5m
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Chickens Pizza",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Pepperoni",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Cheese Pizza",
                            Price = 12.25m
                        },
                        new
                        {
                            Id = 1L,
                            Name = "The Original Neapolitan",
                            Price = 16.25m
                        },
                        new
                        {
                            Id = 6L,
                            Name = "California Style",
                            Price = 15.50m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaOrder", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "Id");

                    b.HasIndex("Id");

                    b.ToTable("PizzaOrder");
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaStore", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.HasKey("Id", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("PizzaStore");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            StoreId = 1L,
                            Inventory = 5
                        },
                        new
                        {
                            Id = 2L,
                            StoreId = 1L,
                            Inventory = 10
                        },
                        new
                        {
                            Id = 3L,
                            StoreId = 1L,
                            Inventory = 20
                        },
                        new
                        {
                            Id = 4L,
                            StoreId = 1L,
                            Inventory = 6
                        },
                        new
                        {
                            Id = 1L,
                            StoreId = 2L,
                            Inventory = 5
                        },
                        new
                        {
                            Id = 2L,
                            StoreId = 2L,
                            Inventory = 10
                        },
                        new
                        {
                            Id = 3L,
                            StoreId = 2L,
                            Inventory = 20
                        },
                        new
                        {
                            Id = 4L,
                            StoreId = 2L,
                            Inventory = 6
                        },
                        new
                        {
                            Id = 5L,
                            StoreId = 3L,
                            Inventory = 6
                        },
                        new
                        {
                            Id = 6L,
                            StoreId = 3L,
                            Inventory = 4
                        },
                        new
                        {
                            Id = 1L,
                            StoreId = 3L,
                            Inventory = 7
                        },
                        new
                        {
                            Id = 2L,
                            StoreId = 3L,
                            Inventory = 6
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Manager = "fred",
                            Name = "Dominos",
                            location = "123 bcd st, Arlington tx"
                        },
                        new
                        {
                            Id = 2L,
                            Manager = "john",
                            Name = "Pizza Hut",
                            location = "456 DeF, Arlington Tx"
                        },
                        new
                        {
                            Id = 3L,
                            Manager = "mark",
                            Name = "Papa John's",
                            location = "456 DeF, Arlington Tx"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "tango",
                            email = "tango@gmail.com",
                            lastname = "Tew",
                            password = "123",
                            type = "user",
                            username = "tango"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Andrew",
                            email = "tango@gmail.com",
                            lastname = "AGatep",
                            password = "123",
                            type = "user",
                            username = "drew"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Mark",
                            email = "mark@gmail.com",
                            lastname = "John",
                            password = "456",
                            type = "store",
                            username = "mark"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Dr. Frank",
                            email = "fred@gmail.com",
                            lastname = "Fred",
                            password = "123",
                            type = "store",
                            username = "fred"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "William",
                            email = "john@gmail.com",
                            lastname = "John",
                            password = "123",
                            type = "store",
                            username = "john"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaOrder", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "Pizza")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Order", "Order")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.PizzaStore", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "pizza")
                        .WithMany("PizzaStores")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Store", "Store")
                        .WithMany("PizzaStore")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
